FROM node:14-alpine

WORKDIR /app

ADD package.json package-lock.json ./

RUN apk add --update --no-cache python3 py3-pip make g++ && rm -rf /var/cache/apk/*

RUN npm install

ADD .babelrc .prettierrc .eslintrc.js stylelint.config.js ./

CMD [ "npm", "run", "dev" ]