@startuml Login activity diagram
start
if (Is logged in?) then (no)
  :Login form;
  if (Forgot password?) then (no)
  :Submit login form;
  else (yes)
    repeat
    :Password reset form;
    repeat while (Is form correctly filled?)
    :Password reset confirmation;
    stop
  endif

  if (Is user registered?) then (no)
    repeat
      :Sign up form;
    repeat while (Is form correctly filled?)
      :Sign up confirmation;
    stop
  else (yes)
  endif
else (yes)
endif
:Login sucessful;
stop
@enduml