@startuml Memory search activity diagram
start
:Memory Feed;
note right
  Search can be performed
  also in the Map view.
end note
:Search;
  split
    :Search by place name;
  split again
    :Search by current location;
  split again
    :Search by favorite places;
  endsplit
:View with results;
note right
  Memory Feed view shows results
  as a feed list. Map View shows
  results as icons in a map. In
  either case, user can select
  a specific memory to view.
end note
:Selected memory view;
end
@enduml