@startuml Usecases

actor User1 as user1
actor User2 as user2

package Memory {
  usecase "Create" as UC1
  usecase "Edit" as UC2
  usecase "Search" as UC3
  usecase "Favorite" as UC4
  usecase "View" as UC5
  usecase "Delete" as UC6
}

package Place {
  usecase "Search" as UC7
  usecase "Associate memories to" as UC8
  usecase "Favorite" as UC9
  usecase "View" as UC10
}

note right of (user1)
 User 1  illustrates the "creator"
 use case. They can create, edit
 and delete memories, as well
 as associate their memories to places.
end note

user1 --> UC1
user1 --> UC2
user1 --> UC6
user1 --> UC8

note left of (user2)
 User 2 illustrates the "browser"
 use case. They can search, view
 and favorite places or memories.
end note

user2 ----> UC3
user2 ----> UC4
user2 ----> UC7
user2 ----> UC9
user2 ----> UC5
user2 ----> UC10

@enduml