const User = require('./user')
const Memory = require('./memory')
const Place = require('./place')

const mateus = new User('Mateus', 'me@mateus.com')
const berlin = new Place({ latitude: 1, longitude: 1 })
const mateusMemory = new Memory('Once upon a time...')
mateus.addMemory(mateusMemory, berlin)
console.log(mateus.memories)
console.log(berlin)

const paloma = new User('Paloma', 'p@paloma.com')
paloma.favoriteMemory(mateusMemory)
paloma.favoritePlace(berlin)
mateus.memories.forEach(item => console.log(`memory: ${item.text}, favorites: ${item.favoriteCount}`))
